routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */



Auth::routes();
Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/', 'MainController@main')->name('main');
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/emailverification', 'MainController@emailverification')->name('emailverification');
    Route::post('/emailverificationpost', 'MainController@emailverificationpost')->name('emailverificationpost');
    Route::post('/updateprofile', 'MainController@updateprofilePost')->name('update.profilePost');
    Route::get('/updateprofile', 'MainController@updateprofile')->name('update.profile');
    Route::post('/changeprofile', 'MainController@changeprofile')->name('changeprofile');
    Route::post('/changecover', 'MainController@changecover')->name('changecover');
    Route::post('/changestatustofree', 'MainController@changestatustofree')->name('changestatustofree');
    Route::post('/searching', 'MainController@searching')->name('searching');
    Route::get('/profile/{id}', 'MainController@profile')->name('profile');
    Route::get('/addcontact/{id}', 'MainController@addcontact')->name('addcontact');
    Route::post('/getcontactlist', 'MainController@getcontactlist')->name('getcontactlist');
    Route::get('/removecontact/{id}', 'MainController@removecontact')->name('removecontact');
    Route::get('/blockcontact/{id}', 'MainController@blockcontact')->name('blockcontact');
    Route::get('/unblockcontact/{id}', 'MainController@unblockcontact')->name('unblockcontact');
    Route::post('/getblockcontactlist', 'MainController@getblockcontactlist')->name('getblockcontactlist');
    Route::post('/addnote', 'MainController@addnote')->name('addnote');
    Route::post('/updatepolicy', 'MainController@updatepolicy')->name('updatepolicy');
    Route::post('/profileattachment', 'UserDocumentsController@profileattachment')->name('profileattachment');
    Route::get('/download/{id}', 'UserDocumentsController@download')->name('download');
    Route::post('/uploadvideo', 'MainController@uploadvideo')->name('upload.video');
    Route::get('/loadmap', 'MainController@loadmap')->name('loadmap');
    Route::post('/savelatlng', 'MainController@savelatlng')->name('savelatlng');
    Route::post('/getlatlng', 'MainController@getlatlng')->name('getlatlng');
    Route::post('/ajax-update-hours-rate', 'MainController@ajaxUpdateHoursRate')->name('ajaxUpdateHoursRate');
    Route::post('/ajax-update-language', 'MainController@ajaxUpdatelanguage')->name('ajaxUpdatelanguage');
    Route::post('/ajax-update-website', 'MainController@ajaxUpdateWebsite')->name('ajaxUpdateWebsite');
    Route::post('/ajax-update-paragraph-title', 'MainController@ajaxUpdateParagraphTitle')->name('ajaxUpdateParagraphTitle');
    Route::post('/ajax-update-paragraph', 'MainController@ajaxUpdateParagraph')->name('ajaxUpdateParagraph');
    Route::get('/setting', 'MainController@setting')->name('setting');
    Route::post('/ajax-add-language', 'MainController@ajaxAddlanguage')->name('ajaxAddlanguage');
    Route::post('/ajax-remove-language', 'MainController@ajaxRemovelanguage')->name('ajaxRemovelanguage');
    Route::post('/ajax-save-user-language', 'MainController@ajaxSaveUserlanguage')->name('ajaxSaveUserlanguage');

    Route::post('/ajax-get-user-language', 'MainController@ajaxGetUserlanguage')->name('ajaxGetUserlanguage');


    Route::post('/setloginlocation', 'MainController@setloginlocation')->name('setloginlocation');
    Route::get('/download-profile-attachment-/{id}', 'UserDocumentsController@downloadProfileAttachment')->name('download.profile.detail.attachments');
    Route::post('/ajax-add-category', 'CategoryController@ajaxAddCategory')->name('ajaxAddCategory');
    Route::post('/ajax-add-category', 'CategoryController@ajaxAddCategory')->name('ajaxAddCategory');
    Route::post('/ajax-add-sub-category', 'CategoryController@ajaxSubAddCategory')->name('ajaxSubAddCategory');
    Route::post('/ajax-get-category', 'CategoryController@ajaxGetCategory')->name('ajaxGetCategory');
    Route::post('/ajax-sub-category-delete', 'CategoryController@ajaxSubCategoryDelete')->name('ajaxSubCategoryDelete');
    Route::post('/ajax-sub-category-edit', 'CategoryController@ajaxSubCategoryEdit')->name('ajaxSubCategoryEdit');
    Route::post('/ajax-add-sub-category-new', 'CategoryController@ajaxSubAddCategoryIfEmpty')->name('ajaxSubAddCategoryIfEmpty');
    Route::post('/ajax-move-category', 'CategoryController@ajaxMoveCategory')->name('ajaxMoveCategory');

    Route::get('/add-training', 'TrainingController@addTraining')->name('addTraining');
    Route::get('/add-training/{id}/{question?}', 'TrainingController@addTrainings')->name('addTrainingPage');
    Route::post('/add-training', 'TrainingController@addTrainingPost')->name('addTrainingPost');
    Route::post('/update-training', 'TrainingController@updateTrainingPost')->name('updateTrainingPost');
    Route::get('/delete-training/{id}', 'TrainingController@deleteTraining')->name('deleteTraining');

    Route::get('/quiz', 'TrainingController@quiz_reqult')->name('quiz');
    Route::get('/exam', 'TrainingController@initExamMode')->name('initExamMode');
    Route::get('/exam/{id}/{question?}', 'TrainingController@questionExamMode')->name('questionExamMode');
    Route::post('/exam-mode/', 'TrainingController@submitExamAnswer')->name('submitExamAnswer');
    Route::get('/exam-finished/{id}', 'TrainingController@examFinished')->name('examFinished');

    Route::get('/training', 'TrainingController@initTrainingMode')->name('initTrainingMode');
    Route::get('/training/{id}/{question?}', 'TrainingController@questionTrainingMode')->name('questionTrainingMode');
    Route::post('/training-mode/', 'TrainingController@submitTrainingAnswer')->name('submitTrainingAnswer');
    Route::get('/training-finished/{id}', 'TrainingController@trainingFinished')->name('trainingFinished');
    Route::get('/publish/{id}', 'TrainingController@publishExam')->name('publishExam');
    

    Route::get('/quiz/{id}', 'TrainingController@quizView')->name('quizView');
    Route::get('/answer/{id}', 'TrainingController@showAnswer')->name('showAnswer');
    
    Route::get('make-post', 'PostController@makePost')->name('makePost');
    Route::post('register-post', 'PostController@submitPost')->name('submitPost');
    

    Route::get('timeline', 'PostController@timeline')->name('timeline');
    Route::get('timeline/sortby/{type?}', 'PostController@timeline')->name('timeline');
    
    Route::post('edit-post', 'PostController@editPost')->name('editPost');
    Route::get('timeline/{id}', 'PostController@userTimeline')->name('userTimeline');
    Route::get('timeline/{id}/sortby/{type?}', 'PostController@userTimeline')->name('userTimeline');
    Route::get('add-archeive-post/{id}', 'PostController@addArcheivePost')->name('addArcheivePost');
    
    Route::get('delete-post/{id}', 'PostController@deleteRoute')->name('deleteRoute');
    Route::post('submit-proposal', 'PostController@submitProposal')->name('submitProposal');
    Route::post('get-proposal', 'PostController@getProposal')->name('getProposal');
    Route::post('process-proposal', 'PostController@processProposal')->name('processProposal');
});


Route::get('logout','Auth\LoginController@logout')->name('logout');
Route::group(['prefix' =>'admin','namespace'=>'Admin','as' => 'admin.'], function () {

    Route::get('/', function () {
        return redirect(route("admin.login"));
    });
    
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/home', 'HomeController@index')->name('home');
    });
});
Route::group(['prefix' =>'agent','namespace'=>'Agent','as' => 'agent.','middleware' => ['agent:agent']], function () {

    Route::get('/', function () {
        return redirect(route("agent.login"));
    });
    //Login Routes...
    Route::get('login','Auth\LoginController@showLoginForm')->name('login');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->name('register');
    Route::group(['middleware' => ['auth:agent']], function () {
        Route::get('/home', 'HomeController@index');
    });
});

Route::post('get-post', 'PostController@getPostData')->name('getPostData');

app/Http/Controllers/Agent/Controller.php
<?php

namespace App\Http\Controllers\Agent;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Agent/HomeController.php
<?php

namespace App\Http\Controllers\Agent;

use Illuminate\Http\Request;
use Closure;
use Auth;
use App\Http\Controllers\Controller;
class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $guard = 'agent';
    public function __construct()
    {
        
        $this->middleware('agent:agent', ['except' => 'logout'])->except('logout');
        /* if(!Auth::guard('agent')->check()){
            return redirect('/agent/login');
        }
        if(Auth::guard('agent')->check()){
            return redirect('/agent/home');
        } */
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /* if(!Auth::guard('agent')->check()){
            return redirect('/agent/login');
        } */
        return view('agent.dashboard.index');
    }
    protected function guard() {
        return Auth::guard('agent:agent');
    }
}

app/Http/Controllers/Agent/PropertyController.php
<?php 
namespace App\Http\Controllers\Agent;

use Illuminate\Http\Request;
use Closure;
use Auth;
use Igaster\LaravelCities\Geo;


class PropertyController extends Controller
{
    public function add_property()
    {   
        return view('agent.property.addproperty');
    }
}

resources/views/agent/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    <!-- Styles -->
    <link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/bootstrap/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/font-awesome/css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/linearicons/style.css') }}">
	<link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/chartist/css/chartist-custom.css') }}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{{ asset('klorofil/assets/css/main.css') }}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{{ asset('klorofil/assets/css/demo.css') }}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    @yield("css")
</head>
<body>
    <div id="app">
    {{-- <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (!Auth::guard("agent")->check())  
                            <li><a href="{{ route('agent.login') }}">Login</a></li>
                            <li><a href="{{ route('agent.register') }}">Register</a></li>
                            
                        @else
                        <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::guard('agent')->user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('agent.logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('agent.logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                        
                    </ul>
                </div>
            </div>
        </nav>--}}

        @yield('content')
    </div>

    <!-- Scripts -->
    <!-- <script src="{{ asset('js/app.js') }}"></script> -->
    <script src="{{ asset('klorofil/assets/vendor/jquery/jquery.min.js') }}"></script>
	<script src="{{ asset('klorofil/assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('klorofil/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
	<script src="{{ asset('klorofil/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
	<script src="{{ asset('klorofil/assets/vendor/chartist/js/chartist.min.js') }}"></script>
	<script src="{{ asset('klorofil/assets/scripts/klorofil-common.js') }}"></script>
</body>
</html>

resources/views/agent/layouts/apps.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Agent Panel</title>



    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">

    <link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/linearicons/style.css') }}">
    <link rel="stylesheet" href="{{ asset('klorofil/assets/vendor/chartist/css/chartist-custom.css') }}">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{ asset('klorofil/assets/css/main.css') }}">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{{ asset('klorofil/assets/css/demo.css') }}">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('klorofil/assets/switcher/switcher.css') }}">
    <link rel="stylesheet" href="{{ asset('countrySelect.min.css') }}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> @yield("css")
</head>

<body>

    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <!-- <div class="brand">
				<a href="{{ url('/') }}"><img height="40px" width="190px" src='{{asset("/img/logo.png")}}' alt="Klorofil Logo" class="img-responsive logo"></a>
            </div> -->
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="brand" style="padding:0">
                    <a href="/agent/home"><img style="height:70px!important"  width="190px" src='{{asset("/img/logo.png")}}' alt="Agent Logo" class="img-responsive logo"></a>
                </div>
                <div class="container-fluid">
                    <div class="navbar-btn">
                        <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                    </div>


                    <div id="navbar-menu">
                        <ul class="nav navbar-nav navbar-right">

                        @if (!Auth::guard("agent")->check())  
                            <li><a href="{{ route('agent.login') }}">Login</a></li>
                            <li><a href="{{ route('agent.register') }}">Register</a></li>
                            
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span>{{ Auth::guard('agent')->user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                                <ul class="dropdown-menu">
                                    <!-- <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
								<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
								<li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li> -->
                                    <li>
                                        <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            <i class="lnr lnr-exit"></i> Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            @endif
                            <!-- <li>
							<a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
						</li> -->
                        </ul>
                    </div>
                </div>
            </nav>
        </nav>

        <div id="sidebar-nav" class="sidebar">
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 95%;">
                <div class="sidebar-scroll" style="overflow: hidden; width: auto; height: 95%;">
                    <nav>

                        <ul class="nav">
                            <li><a href="/agent/home" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>

                            <li><a href="{{ route('agent.add.property') }}" class=""><i class="lnr lnr-code"></i> <span>Add Property</span></a></li>

                            <li><a href="charts.html" class=""><i class="lnr lnr-chart-bars"></i> <span>Charts</span></a></li>

                            <li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>Panels</span></a></li>

                            <li><a href="notifications.html" class=""><i class="lnr lnr-alarm"></i> <span>Notifications</span></a></li>


                            <li>
                                <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Pages</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                                <div id="subPages" class="collapse ">
                                    <ul class="nav">
                                        <li><a href="page-profile.html" class="">Profile</a></li>
                                        <li><a href="page-login.html" class="">Login</a></li>
                                        <li><a href="page-lockscreen.html" class="">Lockscreen</a></li>
                                    </ul>
                                </div>
                            </li>

                            <li><a href="tables.html" class=""><i class="lnr lnr-dice"></i> <span>Tables</span></a></li>

                            <li><a href="typography.html" class=""><i class="lnr lnr-text-format"></i> <span>Typography</span></a></li>

                            <li><a href="icons.html" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li>


                        </ul>
                    </nav>
                </div>
                <div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 496.324px;"></div>
                <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div>
            </div>
        </div>




        @if($msg = session("message"))
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <i class="fa fa-check-circle"></i> {{$msg}}
        </div>



        @endif @if($error = session("error"))
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <i class="fa fa-check-circle"></i> {{$error}}
        </div>
        @endif @yield('content')




        <script src="{{ asset('klorofil/assets/vendor/jquery/jquery.min.js') }}"></script>
        <script src="{{ asset('klorofil/assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ asset('klorofil/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
        <script src="{{ asset('klorofil/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
        <script src="{{ asset('klorofil/assets/vendor/chartist/js/chartist.min.js') }}"></script>
        <script src="{{ asset('klorofil/assets/scripts/klorofil-common.js') }}"></script>

        <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="{{ asset('klorofil/assets/switcher/switcher.js') }}"></script>
        @yield("script");
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">© 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>
    </div>

</body>

</html>